import { useState } from 'react'
import { CalendarDays, ChevronDown, Clock3, Leaf, MapPin, Plane, Search, Users } from 'lucide-react'

const flights = [
  { id: 1, airline: 'TAP Air Portugal', flight: 'TP 088', depart: '22:15', arrive: '11:10', duration: '9h 55m', stops: 0, price: 3248, tag: 'Voo direto', tone: 'emerald' },
  { id: 2, airline: 'LATAM Airlines', flight: 'LA 8146', depart: '20:40', arrive: '14:30', duration: '13h 50m', stops: 1, price: 2989, tag: 'Menor preço', tone: 'indigo' },
  { id: 3, airline: 'Azul Linhas Aéreas', flight: 'AD 8700', depart: '23:50', arrive: '16:05', duration: '12h 15m', stops: 1, price: 3175, tag: 'Eco friendly', tone: 'emerald' },
]

function SearchBar({ searching, onSearch }) {
  const [origin, setOrigin] = useState('GRU — São Paulo')
  const [destination, setDestination] = useState('LIS — Lisboa')
  const [picker, setPicker] = useState(null)
  const [passengers, setPassengers] = useState(1)
  const suggestions = picker === 'origin' ? ['GRU — São Paulo', 'GIG — Rio de Janeiro', 'CNF — Belo Horizonte'] : ['LIS — Lisboa', 'JFK — Nova York', 'CDG — Paris']
  const choose = (value) => { picker === 'origin' ? setOrigin(value) : setDestination(value); setPicker(null) }
  return <div className="rounded-2xl border border-white/70 bg-white p-3 shadow-2xl shadow-indigo-950/10">
    <div className="flex flex-col divide-y divide-slate-200 lg:flex-row lg:divide-x lg:divide-y-0">
      {[['origin', 'Origem', origin], ['destination', 'Destino', destination]].map(([key, label, value]) => <div className="relative min-w-0 flex-1" key={key}><button onClick={() => setPicker(picker === key ? null : key)} className="flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left hover:bg-slate-50"><MapPin className="h-5 w-5 shrink-0 text-indigo-600" /><span className="min-w-0"><small className="block text-slate-500">{label}</small><b className="block truncate">{value}</b></span></button>{picker === key && <div className="absolute z-20 mt-2 w-full min-w-60 overflow-hidden rounded-xl border border-slate-200 bg-white py-1 shadow-xl">{suggestions.map(item => <button onClick={() => choose(item)} className="flex w-full gap-2 px-4 py-3 text-left text-sm hover:bg-indigo-50" key={item}><Plane className="h-4 w-4 text-indigo-600" />{item}</button>)}</div>}</div>)}
      <button className="flex flex-1 items-center gap-3 px-3 py-3 text-left hover:bg-slate-50"><CalendarDays className="h-5 w-5 text-indigo-600" /><span><small className="block text-slate-500">Datas</small><b>12 set — 26 set</b></span></button>
      <div className="relative flex-1"><button onClick={() => setPicker(picker === 'passengers' ? null : 'passengers')} className="flex w-full items-center gap-3 px-3 py-3 text-left hover:bg-slate-50"><Users className="h-5 w-5 text-indigo-600" /><span><small className="block text-slate-500">Viajantes</small><b>{passengers} passageiro{passengers > 1 && 's'}</b></span><ChevronDown className="ml-auto h-4 w-4" /></button>{picker === 'passengers' && <div className="absolute right-0 z-20 mt-2 w-56 rounded-xl border border-slate-200 bg-white p-4 shadow-xl"><div className="flex items-center justify-between"><b>Adultos</b><span className="flex items-center gap-3"><button onClick={() => setPassengers(Math.max(1, passengers - 1))}>−</button>{passengers}<button onClick={() => setPassengers(passengers + 1)}>+</button></span></div></div>}</div>
      <button disabled={searching} onClick={onSearch} className="m-1.5 inline-flex items-center justify-center gap-2 rounded-xl bg-indigo-600 px-7 py-3 font-semibold text-white transition hover:bg-indigo-700 disabled:opacity-70"><Search className="h-5 w-5" />{searching ? 'Buscando...' : 'Buscar'}</button>
    </div>
  </div>
}

function FlightCard({ flight }) { return <article className="grid gap-5 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm transition hover:shadow-md md:grid-cols-[1.15fr_1fr_auto] md:items-center"><div><div className="mb-3 flex items-center gap-2"><span className="grid h-9 w-9 place-items-center rounded-full bg-slate-100 font-bold text-indigo-700">{flight.airline[0]}</span><span><b className="block text-sm">{flight.airline}</b><small className="text-slate-500">{flight.flight} · Econômica</small></span></div><div className="flex items-baseline gap-3"><strong className="text-2xl">{flight.depart}</strong><span className="text-slate-400">GRU</span><span className="text-slate-400">→</span><strong className="text-2xl">{flight.arrive}</strong><span className="text-slate-400">LIS</span></div></div><div><div className="flex items-center gap-2 text-sm text-slate-600"><Clock3 className="h-4 w-4" />{flight.duration}<span className="h-px flex-1 bg-slate-300" /><Plane className="h-4 w-4 text-indigo-600" /></div><div className="mt-2 flex gap-2"><span className={`rounded-full bg-${flight.tone}-50 px-2 py-1 text-xs font-semibold text-${flight.tone}-700`}>{flight.tag}</span>{flight.tag === 'Eco friendly' && <Leaf className="h-4 w-4 text-emerald-600" />}</div></div><div className="md:text-right"><small className="text-slate-500">ida e volta, por pessoa</small><strong className="block text-2xl">R$ {flight.price.toLocaleString('pt-BR')}</strong><button className="mt-2 rounded-lg bg-indigo-600 px-4 py-2 text-sm font-semibold text-white hover:bg-indigo-700">Ver oferta</button></div></article> }

export default function App() { const [searching, setSearching] = useState(false); const [sort, setSort] = useState('Melhor'); const search = () => { setSearching(true); setTimeout(() => setSearching(false), 900) }; const shown = [...flights].sort((a,b) => sort === 'Mais barato' ? a.price-b.price : sort === 'Mais rápido' ? a.duration.localeCompare(b.duration) : a.id-b.id); return <main><header className="mx-auto flex max-w-6xl items-center justify-between px-5 py-5"><a className="flex items-center gap-2 text-xl font-black tracking-tight"><span className="grid h-9 w-9 place-items-center rounded-xl bg-indigo-600 text-white"><Plane className="h-5 w-5" /></span>Celes.ia</a><span className="text-sm font-medium text-slate-600">Flight Intelligence</span></header><section className="bg-gradient-to-br from-indigo-900 via-indigo-700 to-sky-600 px-5 py-14 text-white"><div className="mx-auto max-w-6xl"><p className="mb-3 text-sm font-semibold uppercase tracking-widest text-indigo-200">Voos que fazem sentido</p><h1 className="max-w-2xl text-4xl font-bold tracking-tight md:text-5xl">Encontre sua próxima viagem por um preço melhor.</h1><p className="mt-4 max-w-xl text-indigo-100">Compare companhias, horários e ofertas em uma única busca.</p><div className="mt-8"><SearchBar searching={searching} onSearch={search} /></div></div></section><section className="mx-auto max-w-6xl px-5 py-10"><div className="mb-6 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm text-slate-500">São Paulo para Lisboa · 12–26 de setembro</p><h2 className="text-2xl font-bold">{searching ? 'Procurando as melhores opções...' : '142 voos encontrados'}</h2></div><div className="flex rounded-lg border border-slate-200 bg-white p-1">{['Melhor','Mais barato','Mais rápido'].map(tab => <button onClick={() => setSort(tab)} key={tab} className={`rounded-md px-3 py-2 text-sm font-semibold ${sort === tab ? 'bg-indigo-600 text-white' : 'text-slate-600 hover:bg-slate-100'}`}>{tab}</button>)}</div></div><div className="grid gap-4">{searching ? [1,2,3].map(i => <div key={i} className="h-44 animate-pulse rounded-2xl bg-slate-200" />) : shown.map(flight => <FlightCard key={flight.id} flight={flight} />)}</div></section></main> }
